### PR TITLE
#232 Start & Submission page improvements

### PR DESCRIPTION
**Pull request by CarlosNZ**
Implements remaining scope of #232, namely:
- Start (and Submission) message is evaluated with the expression evaluator before being displayed (as Markdown)
- If no start message is defined, application loads with no start page

Requires [back end branch #232F](https://github.com/openmsupply/application-manager-server/pull/168) to see its functionality:
- launch the **FeatureShowcase** application to see the message using expression evaluation.
- launch **UserRegistration** application to see start page skip.

~~**NOTE**: This still uses the old array format for the evaluator objects. It will need to be updated after #238 is merged, so hopefully that will be approved before this one and I'll merge it back into here and do those changes before this is merged.~~ (Done)

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Will also update Submission page to use the evaluator once #234 is merged.

**Review by nmadruga — CHANGES_REQUESTED** [review]
I'm finding problem when trying to load the applications after the Start page has been displayed. The error showing on the console is this:
Screen Shot 2021-01-08 at 12 54 10 PM

**Comment by CarlosNZ** [comment]
> I'm finding problem when trying to load the applications after the Start page has been displayed.
> It can create the application but is failing to show the initial page. The error showing on the console is this:
> Screen Shot 2021-01-08 at 12 54 10 PM

Is there a particular template this is happening with, or all of them?

**Comment by nmadruga** [comment]
Yey! Finally working. The browser was confusing the evaluatorExpression package versions, it would work fine on another private instance that I was using to debug, but not for the regular Google Chrome instances. Solved now after clear my browser cached data.

**Review by nmadruga — APPROVED** [review]
Thanks for putting all of this together. Looks great!

I'm seeing some errors in the console which are related to 2 bugs in development introduced before this PR, so not problem with that. I think this one is good.

**Pull request merged**
