### PR TITLE
#175 show review progress

### LINKED ISSUE #175: Show progress of review on the section
Screen Shot 2021-01-05 at 2 05 52 PM
Screen Shot 2021-01-05 at 2 06 01 PM

### PR DESCRIPTION
**Pull request by nmadruga**
~~Fixes #175~~

Branched from PR #320, please merge it before this one.

### Summary of changes
- Add section progress in **Review Start** and **Review** pages, with current review progress:
  - Progress bar show **reviewed** / **total responses** in green when all is Approved
  - Progress bar show **reviewed** / **total responses** in red if at least one is Denied
- In the review **Start** also display the label `completed` for all reviews as Approved or `(?) declined` for reviews with declined responses. This is currently displaying the status of last review/consolidation done for application.

### Examples
Run the `yarn database_init` script on back-end to start with reviews with specific status, as below:

#### Not started
Screen Shot 2021-02-15 at 6 05 47 PM

#### Review submitted with progress
Screen Shot 2021-02-15 at 5 01 06 PM

### Review in draft with some progress 
Screen Shot 2021-02-15 at 5 01 30 PM

#### Review with Changes requested
In this case the progress displayed is the latest review_responses - so the consolidator review. I think that might be a good thing, but it can look strange to see another person review on your review start page.
Screen Shot 2021-02-15 at 5 00 31 PM

#### On Review page
Screen Shot 2021-02-15 at 6 29 15 PM

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Haven't looked at the code yet, but just some initial observations when running it:

107908424-e1555c00-6fba-11eb-8e2c-736ca3f7a5d8

- Should there be a status showing here? (And if not, maybe hide the element rather than have it empty)

Screen Shot 2021-02-16 at 2 02 36 PM

- When both sections are assigned to me, once I've started the review, the home page then shows nothing in the progress if I haven't started a Section. I think you'd expect it to still show "Assigned to you" like it did before if I haven't touched it yet, or some other indicator of progress, not just blank. Is this too much hassle to implement?

**Comment by CarlosNZ** [comment]
Haven't looked at the code yet, but just some initial observations when running it:

107908424-e1555c00-6fba-11eb-8e2c-736ca3f7a5d8

- Should there be a status showing here? (And if not, maybe hide the element rather than have it empty)
----
Screen Shot 2021-02-16 at 2 02 36 PM

- When both sections are assigned to me, once I've started the review, the home page then shows nothing in the progress if I haven't started a Section. I think you'd expect it to still show "Assigned to you" like it did before if I haven't touched it yet, or some other indicator of progress, not just blank. Is this too much hassle to implement?

- And can you fix the conflicts at some point, thanks?

Looking really nice though. 👍

**Comment by nmadruga** [comment]
Thanks for having a look on this one already! 

> Should there be a status showing here? (And if not, maybe hide the element rather than have it empty)

In this case there is no review yet. I think it would be nice to show some status like `Not started`. Will work on  that next.

> When both sections are assigned to me, once I've started the review, the home page then shows nothing in the progress if I haven't started a Section. I think you'd expect it to still show "Assigned to you" like it did before if I haven't touched it yet, or some other indicator of progress, not just blank. Is this too much hassle to implement?

My intention was to mimic the same behaviour the user have on the Application. So I intentionally removed from the start page - although was maintained in the Review page. I'll revert to show `Assigned to you` in both cases then. : )

> And can you fix the conflicts at some point, thanks?

Done

**Comment by nmadruga** [comment]
Closing this one without merge to be replaced with new PR using current structure \o/

**Pull request closed without merging**
