### PR TITLE
#477 part 2 show history panel

### LINKED ISSUE #477: Show all the history on for all the previous responses and review (from consolidator and reviewer)
Just to show the list as in:
Screen Shot 2021-05-06 at 8 38 29 PM

Can be done on a separated issues, or as part of this one: selecting one review from the list:
Screen Shot 2021-05-06 at 8 39 23 PM

This is how it would be displaying the current - in preview mode (to be done in [Epic #33 - Application to PDF templates](#333)):
Screen Shot 2021-05-06 at 8 39 04 PM

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #477 

### Linked PRs
- Backend PR [#477F](https://github.com/openmsupply/application-manager-server/pull/431) 
- Base on PR #798 
- ~~Based on PR #792~~

### Changes
- 2 queries to get all reviewResponses and applicationResponses related to a question in one template (for an application), thought it was easier to set conditions to filter reviews for applicant making specific ones for Applicant and Reviewer.
- New **hook** `userGetQuestionHistory` to call either one of the queries and built the `historyList` using the type `HistoryElement`. I tried to simplify (for now) so both reviewResponse and applicantResponse can be stored in the same.
- TODO: Show SummaryView for an ApplicantResponse - for now is just showing the text
- When the button "View history" is available, click on the button will popup the modal with the history for that question.
- Some work to do around the layout and designs (not defined yet - so I described the one I'm basing on in the issue #477 
- TODO: ReviewDecision is also just showing the decision stored in db - not localisation. Was thinking if it would be better to just use `DecisionLabel` component to render a reviewResponse. And in that case, might need to change that one to receive more generic props. What do you think?

### CODE REVIEW

**Comment by nmadruga** [comment]
I noticed a problem that is happening now and would probably need another issue to fix:
When we do a Consolidation, the lower level review responses are getting an updated (I think due to the link to the consolidation review or to update the `recommended_applicant_visibility`, but what happens is that when we display the elements in order, the consolidation and review are somehow missed. And the reason is the `timeUpdated` on lower level review getting updated after a consolidation starts.

**Comment by nmadruga** [comment]
@andreievg and @CarlosNZ sorry I couldn't get much done on this today with all the meeting I wasn't able to focus so much. I wanted to have a look on the problem we recreate the problem we saw when opening a History panel couldn't replicate on this branch based on master.

**Comment by CarlosNZ** [comment]
@nmadruga Can you save and share a snapshot of your database where we can see a more fully-formed History. I'm not sure how to easily create a situation where we can see a decent history. In particular, it'd be good to see how it looks with:
 - Multiple stages
 - what happens when the History list goes beyond the viewport
 - How elements other than Text responses look (i.e. Ingredients list, Images, etc.)

**Comment by nmadruga** [comment]
> @nmadruga Can you save and share a snapshot of your database where we can see a more fully-formed History.

I don't have snapshots feature available in this branch. I think we need to merge existing PR first so I can do that simply for now. If there is a simple way please let me know. 
What I do now to test this is:
### Test1 - Reviewer history
- Log in as **Reviewer1** and on the Dashboard click on the "Changes Requested" application
- Start and click on the `Update` to change a previous review
- After doing that you can see the **View History** button
### Test 2- Applicant history
- Log in as **Valerio** and on the Dashboard click on the "Changes Required" application
- Start and changed to "Something else" then click **Review and Summary**
- After doing that you can see the **View History** button

> it'd be good to see how it looks with:
> * Multiple stages

Using **Test 1** you can see these elements in the history:
The separation in stages isn't added as part of this PR (WIP for issue #811) but here are all elements from 2 stages. The ones on the top are related to "Assessment" and the bottom one is related to "Screening".
Screen Shot 2021-07-07 at 11 22 21 AM
Applicant response is the one on the bottom (when you scroll)
Screen Shot 2021-07-07 at 11 22 28 AM

Using **Test 2** you can see these elements in the history:
Screen Shot 2021-07-07 at 11 27 46 AM

> * what happens when the History list goes beyond the viewport

Automatic vertical scrollbar

> * How elements other than Text responses look (i.e. Ingredients list, Images, etc.)
Exempla (image):
Screen Shot 2021-07-07 at 11 30 21 AM

For list builder we need some more specific solution. I don't know now, but I really think that the idea of using exisiting components to display here would show cluttered + would required a lot more parameters to be passed to the History Panel.

**Comment by CarlosNZ** [comment]
Thanks for the testing guide, I'll work through it now.

> For list builder we need some more specific solution

I made an improvement to the listBuilder text display for a problem that came up in the demo -- there is a PR for it -- that should make the display of listbuilder a bit more reasonable: https://github.com/openmsupply/application-manager-web-app/pull/814

**Comment by CarlosNZ** [comment]
This is looking really good, nice work. I just have one question -- what happens with the different Stages?  I know you were working on something to break up the history into stages, but is that in another PR?

**Comment by nmadruga** [comment]
It's not in a PR yet, but I should get back to it today and work on that solution you gave to add stages to each application_response so we know where to show in the History Panel.

**Review by CarlosNZ — APPROVED** [review]
Cool, I'm happy to merge this (and the one it's merging into) now. It looks like you've done a pretty thorough re-factor of the review elements, etc. but I haven't gone through it with a fine-toothed comb or anything (it's too big!). And it's working well, so that's the main thing for now.

I think there are some minor UI issues that could be improved (the plain black-and-white look is a bit drab), but there's probably not much point trying to do much more with that until we get a bit further along/get some designer input.

Nice work, don't know if @andreievg wants to add any more, but it's good to go for me.

**Pull request merged**
