### PR TITLE
#589 Bug fix: Improve assignment row labels

### LINKED ISSUE #589: Change validation on User Registration to allow 6 digits

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #589 

### Back-end PR
[#311F](https://github.com/openmsupply/application-manager-server/pull/302)

### Based on PR
#311 

### Changes
- Change labels displayed for each assignments on `RowSectionRowAssigned` when:
   - Section can be self-assigned (current user):
  Screen Shot 2021-04-14 at 10 18 44 AM

   - Section can be self-assigned (another user):
  Screen Shot 2021-04-14 at 10 19 26 AM

  - Section is assigned (current user):
  Screen Shot 2021-04-14 at 10 18 35 AM

  - Section is locked (another user):
  Screen Shot 2021-04-14 at 10 27 04 AM

  - Section reviewed (or being reviewed) by another user:
  Screen Shot 2021-04-14 at 10 19 30 AM

[UPDATED 14/04/2021]
- Added `trigger` under `reviewAssignments` nodes on the `getReviewInfo` to wait for reviewAssignment.status changes. For example when the user does Self-Assignment, the `ReviewHome` should wait for new statuses of other assignment to get updated via action.

When loading a review page that can be assigned by **Consolidator 1** or **Consolidator 2** (and has been reviewed on level 1 in the same stage) this is how the page will display:
Screen Shot 2021-04-14 at 10 19 12 AM
Screen Shot 2021-04-14 at 10 19 20 AM

After the **Consolidator 2** self-assign to review, now it should show as locked to **Consolidator 1**:
Screen Shot 2021-04-14 at 10 19 54 AM
Screen Shot 2021-04-14 at 10 20 03 AM

### Pending
~~- There is still a problem after the self-assignment is done the other possible self-assignment don't get updated to show locked - it needs a page refresh~~ FIXED

### CODE REVIEW

**Comment by nmadruga** [comment]
@andreievg and @CarlosNZ, another PR here for 7 days. Please have a look today if time available.

**Review by CarlosNZ — COMMENTED** [review]
Cool, it's looking great and working well, as far as I can tell.

One slightly out-of-scope fix -- only bother if it's as simple as I think it is:
The "Back" link icon on the Review page is incorrect. Currently it's:
```
to={`/applications?type=${structure.info.type}`}
```
but it should be `structure.info.code` (or templateCode, whatever it's called)

**Comment by nmadruga** [comment]
> Cool, it's looking great and working well, as far as I can tell.
> 
> One slightly out-of-scope fix -- only bother if it's as simple as I think it is:
> The "Back" link icon on the Review page is incorrect. Currently it's:
> 
> ```
> to={`/applications?type=${structure.info.type}`}
> ```
> 
> but it should be `structure.info.code` (or templateCode, whatever it's called)

Done. Thanks for the review!

Can this be merged?

**Comment by nmadruga** [comment]
Oh no... I commited to the wrong branch : P 

Will move the commit to this branch, 1 minute.

**Comment by nmadruga** [comment]
Done 🎉

**Review by CarlosNZ — APPROVED** [review]
Great, thanks.

**Pull request merged**
