### PR TITLE
905 stabilise outcomes

### PR DESCRIPTION
**Pull request by andreievg**
fixes: #905 

Just before making this PR i looked at the issue again and realised there are some suggestions form Carl. Sorry i missed them will revise tomorrow.

I had to move some things around before making this PR since code needed to be split up a bit, actual changes are (this is after reshuffle and before new changes):  https://github.com/openmsupply/application-manager-web-app/compare/905-after-reshuffle..905-stabilise-outcomes

### Changes

* Added a context as a wrapper (since we need to do queries that are pre-requisite to other, the schema query should be after we have tables and columns for from outcome displays)
* created a query for schema columns
* use this query to filter out columns in table and detail of outcomes displays before query for them are build
* filtered out tables that don't exists yet for applicationLink (there was a nasty error showing in console before that)

Sorry i forgot again to branch from dev (too many changes if i try to re-base, I'll merge develop into this and re-base)

### CODE REVIEW

**Review by CarlosNZ — APPROVED** [review]
Cool, looks good to fix the main problems.

**Comment by nmadruga** [comment]
Is this one ready to merge to `main` @CarlosNZ ?

**Comment by CarlosNZ** [comment]
> Is this one ready to merge to `main` @CarlosNZ ?

Thought we wanted to go via develop all the time?

**Comment by andreievg** [comment]
Changes base, and resolved conflicts

**Pull request merged**
