### PR TITLE
#1142 Missing operators in template builder

### LINKED ISSUE #1142: Add "objectFunctions" operator to Template Builder
Currently missing, so can only add via JSON.

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1142 

- update evaluator version (was missing an Operator Type)
- Add "objectFunctions" operator to GUI
- Add "POST" operator to GUI
- Tidy up existing operators in GUI

Edit: Also added a small fix to refresh the Snapshots list after saving a new one (something that's been annoying me for a while) -- c53d18ea

### CODE REVIEW

**Comment by nmadruga** [comment]
> Edit: Also added a small fix to refresh the Snapshots list after saving a new one (something that's been annoying me for a while) -- [c53d18e](https://github.com/openmsupply/application-manager-web-app/commit/c53d18ea1d876122a44469e93d96617ddc7dc1bf)

Yey - bery nice. I'll strt reviewing this one now

**Comment by nmadruga** [comment]
Ok if I revert these changes so we keep the release-candidate as 0.2.0-3 again? I would also remove the tags pushed.
Screen Shot 2022-04-08 at 9 06 37 AM

My plan is to upgrade the server today to 0.2.0-4 today with latest changes merged to `develop`.

**Comment by CarlosNZ** [comment]
> My plan is to upgrade the server today to 0.2.0-4 today with latest changes merged to `develop`.

Sure, although I don't think it really matters if we have build tags that we don't release -- they're "pre-release" tags. I'll try and stick to building branches rather than tags if it's just for testing purposes though.

FYI -- I have a PR that I'm going to publish shortly that deals with remaining docker quirks, so we'll probably want that for the next build.

**Comment by nmadruga** [comment]
Ok cool - I won't bother removing the tags in that case. We just release the next available tag to the server. 
And no problem to wait for your PR to go in. I also would like the Portuguese stuff to be included today - if all in there. I still need to check

**Review by nmadruga — APPROVED** [review]
LGTM

**Pull request merged**
