### PR TITLE
Localisations in lookup tables UI

### PR DESCRIPTION
**Pull request by nmadruga**

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Thanks -- think the base branch is wrong though, I see changes from several of my PRs in here.

**Comment by nmadruga** [comment]
Oh - yea... This is supposed to go on top of the fix done on #997. Thanks, will update this now : )

**Comment by nmadruga** [comment]
Nope. Didn't work - I'll need to created another branch to base this from "#587B-fix-viewing-lookup-tables-in-develop" without having to deal with conflicts. One minute, I'll close this one after that's done.

**Comment by nmadruga** [comment]
Ah! Much better -> New PR here:  #1002

**Pull request closed without merging**
