### PR TITLE
#143 unify types reusing hook get section elements

### PR DESCRIPTION
**Pull request by nmadruga**
Ok, This changes are intended to help by using the same object structure to build up the Application page and Application summary. Ideally we would use a single query to either get all **elements & responses** for the entire application or a section, but for now I'm just create a second hook that does pretty much the same as  the existing getElementsAndResponses hook.

- Existing hook: `useGetResponsesAndElementState`
- New hook: `useGetSectionElementAndResponses`.

Ex: response from `useGetSectionElementAndResponses`
```
SectionPagesElement: {
  [1]: // Page 1
  [
      { 
         element: {
            category: "QUESTION"
            code: "Q1"
           elementTypePluginCode: "shortText"
           id: 2
           isEditable: true
           isRequired: true
           isVisible: true
           parameters: {label: "First Name"}
           section: {index: 0, page: 1}
           title: "First Name"
         },
         response : {
           id: 1
          isValid: false
          value: {text: "Craig"}
         }
      },
      { element: ElementState, response: ResponseFull | undefined },
      ...
  ],
  [2]: ElementAndResponse[] // Page 2
}
```

## Changes
- Rename query `getSectionElements` to `getSectionElementsAndResponses`
- Deleted hook `useLoadElementsOfSection`  => Created `useGetSectionElementAndResponses`
- Separated `evaluateElementExpressions` as a helper function
- Change `ApplicationViewWrapper` to stop receiving GraphQL types, instead get the transformed types (after running the evaluation of responses):
    - `currentResponse` from GraphQL `ApplicationResponse` to `ResponseFull`
    - Remove: `templateElement`
    - Added: `parameters`, `code`, `pluginCode` from GraphQL  `TemplateElement`
- Change `SummaryViewWrapper` props to receive the element as `ElementState` and response as `ResponseFull`

### To be finished
The other new hook `useListSectionsInSummary` is not working, and not in use yet! The Summary still uses the OLD way of getting all the question/elements from another query, which I'm trying to unify here.

I'm creating this PR now so we can have a discussing for the existing points and I'll be continuing this work on another PR to use the new hook `useListSectionsInSummary` (which should basically call the `useGetSectionElementAndResponses` for all sections and this way get a structured list of sections, pages and **elements & responses** to display.

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Screen Shot 2020-11-27 at 4 19 04 PM
Getting this error. I'm guessing there used to be code that meant it knew not to look for PageBreak in plugins folder, but now it's trying to find one.

**Comment by nmadruga** [comment]
> Getting this error. I'm guessing there used to be code that meant it knew not to look for PageBreak in plugins folder, but now it's trying to find one.

Fixed now. Yes, I missed one place that was removing this elements from the list.

**Comment by CarlosNZ** [comment]
Replacement PR in progress 😎

Do you want to close this, @nmadruga ?

**Comment by nmadruga** [comment]
Closing after rewriting a simpler version with Carl

**Pull request closed without merging**
