### PR TITLE
TB - Nice little feature to add actions at the top or bottom of list

### PR DESCRIPTION
**Pull request by nmadruga**
Partial fix for issues in https://github.com/openmsupply/application-manager-server/issues/506

In Template list of actions - helpful when we need to create one in the beginning of a list

How it looks:
Screen Shot 2021-09-03 at 3 11 34 PM

### CODE REVIEW

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
One main problem -- it adds actions even when the template should be uneditable (i.e not in Draft or Disabled).

I'm not sure about the UI. It's very unintuitive. Why not just have a toggle switch next to the "Add action" button, set to either "top" or "bottom", then the "Add" button can just work as before (but respecting the state of the toggle switch)?

**Comment by nmadruga** [comment]
> I'm not sure about the UI. It's very unintuitive. Why not just have a toggle switch next to the "Add action" button, set to either "top" or "bottom", then the "Add" button can just work as before (but respecting the state of the toggle switch)?

Sure. I can change this to be a toggle. Working on this for the next 15 minutes - I don't want to take too long since it's a non-priority. But would be good to shorten this list of PRs today.

**Comment by nmadruga** [comment]
Change done @CarlosNZ 

Have also added some localisation strings to the Action tab and got carried and created a non-priority PR to combine the Action tools vertically aligned in the first column of each row. See if you like this option, not a priority though: #1001

**Comment by nmadruga** [comment]
@CarlosNZ Ok to merge this one now?

**Comment by CarlosNZ** [comment]
> @CarlosNZ Ok to merge this one now?

hang on, I'll have another quick look now.

**Comment by CarlosNZ** [comment]
> > @CarlosNZ Ok to merge this one now?
> 
> hang on, I'll have another quick look now.

Can you update this from develop? Doesn't work with current back-end.

**Comment by nmadruga** [comment]
Done

**Review by CarlosNZ — APPROVED** [review]
Looks great, thanks.

One tiny little request if you think it's worth it -- I think the default state for the toggle should be "off", it's more natural to add things to the bottom of a list. Inserting at the top seems more like the "non-default" option.

**Comment by nmadruga** [comment]
> One tiny little request if you think it's worth it -- I think the default state for the toggle should be "off", it's more natural to add things to the bottom of a list. Inserting at the top seems more like the "non-default" option.

Thank you. Agreed, and done.

**Pull request merged**
