### PR TITLE
#879 Show different title when application is completed

### LINKED ISSUE #879: Summary page shouldn't show "Review and Submit" for completed applications

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #879

##Linked PR 
Based on PR #984 

Very quick adding to help with linked application of outcomes to have better title - Completed application

Application before submission:
Screen Shot 2021-09-17 at 7 02 43 PM

Application after submission:
Screen Shot 2021-09-17 at 7 03 17 PM

### CODE REVIEW

**Comment by CarlosNZ** [comment]
Just a suggestion -- it might good to show the application title as well, as it's not visible anywhere else, and it'd be a good way to quickly see what the application is for without scrolling through all the questions.

e.g
## Company Registration: Pharma 101
### Application completed

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Just a suggestion -- it might good to show the application name as well, as it's not visible anywhere else, and it'd be a good way to quickly see what the application is for without scrolling through all the questions.

e.g
## Company Registration: Pharma 101
### Application completed

**Comment by nmadruga** [comment]
> Just a suggestion -- it might good to show the application name as well, as it's not visible anywhere else, and it'd be a good way to quickly see what the application is for without scrolling through all the questions.
> 
> e.g
> 
> ## Company Registration: Pharma 101
> ### Application completed

Better?
Screen Shot 2021-09-23 at 2 51 43 PM

**Comment by nmadruga** [comment]
Or perhaps:
Screen Shot 2021-09-23 at 2 57 30 PM

commiting this one which I like better : ) Let me know your thought too

**Comment by CarlosNZ** [comment]
> commiting this one which I like better : ) Let me know your thought too

Yeah, that seems better I think. Thanks.

**Review by CarlosNZ — APPROVED** [review]
Nice. 👍

**Pull request merged**
