### PR TITLE
#52 Element rendering fix

### PR DESCRIPTION
**Pull request by CarlosNZ**
This is just a basic fix for #52. Main problem was the `useGetSectionElementsQuery` query was not fetching `elementTypePluginCode`. 

Also, removed `ApplicationQuestion` component, since it was doing the same thing as the ApplicationViewWrapper.

Have hard-coded an initial `pluginManifest` in `pluginProvider` as per @andreievg's example.

This is not meant to be a complete implementation for the rendering of elements, some values are still hard-coded (`isVisible` etc.)

Will use this as basic for using the evaluator next. Let me know if you think I should do any additional changes in this issue.

### CODE REVIEW

**Review by nmadruga — APPROVED** [review]
Perfect. It is actually a small PR, but because all of the style changes it looks bigger.
I'm happy to merge this one now, hopefully we won't get too many conflicts with the PR
#54 :octocat:

**Comment by CarlosNZ** [comment]
Going to re-do this one to base on #54, so don't review this just yet.

**Review by nmadruga — CHANGES_REQUESTED** [review]
As per previous comment. Flagging this PR should wait to be merged.

**Comment by CarlosNZ** [comment]
Closing -- replaced by #57

**Pull request closed without merging**
