### PR TITLE
Portuguese strings v1.1

### PR DESCRIPTION
**Pull request by nmadruga**
### Linked PR
- Back-end https://github.com/openmsupply/application-manager-server/pull/571

### Changes
- Add new strings in Portuguese and set to use Portuguese (until we have localisation in place)
- Some plugins have both files and using Portugese:
  - file Upload
  - List builder
  - password

### CODE REVIEW

**Comment by nmadruga** [comment]
> Some plugins have both files and using Portugese:
> * file Upload
> * List builder
> * password

Hi @CarlosNZ I iwas thinking about closing this PR since you have already moved most strings to the localiisation PR, although I think this translatiions weren't included for plugins. Can you include those too please?

**Comment by CarlosNZ** [comment]
> Hi, @CarlosNZ I was thinking about closing this PR since you have already moved most strings to the localisation PR, although I think these translatiions weren't included for plugins. Can you include those too, please?

Sure, thanks for the reminder.

**Comment by CarlosNZ** [comment]
> Hi, @CarlosNZ I was thinking about closing this PR since you have already moved most strings to the localisation PR, although I think these translatiions weren't included for plugins. Can you include those too, please?

That's done now, in `#localisation` branch

**Comment by nmadruga** [comment]
> > Hi, @CarlosNZ I was thinking about closing this PR since you have already moved most strings to the localisation PR, although I think these translatiions weren't included for plugins. Can you include those too, please?
> 
> That's done now, in `#localisation` branch

Thank you!! I'll have another look on that one

**Pull request closed without merging**
