### PR TITLE
List builder summary view fix

### LINKED ISSUE #769: Bug fix -- listBuilder crashing when one of the replacement substrings is blank
Happens when filling in Listbuilder form and leaving a non-required field empty (i.e. it's `value.text` is undefined). Not apparent if tabbing through the fields, as entering a field causes it's "value.text" to be "" rather than undefined.

EDIT: Should be fixed by #770

### PR DESCRIPTION
**Pull request by CarlosNZ**
Quick fix for List builder SummaryView when no `displayFormat` parameter is specified.

I already fixed the same problem for the Search plugin, but forgot that it would occur here too.

Just used the same default displayFormat as the ApplicationView, so won't fail when rendering in Summary page.

@nmadruga -- this will fix your listBuilder item not working on Summary page.

---

Update: This also fixes #769 -- was crashing when field inputs were undefined, now has `?.` checking b05368fa

### CODE REVIEW

**Comment by nmadruga** [comment]
@CarlosNZ please fix conflicts on this one. I would like to test this with Company license, but not sure how to without merging more branches togheter.... Maybe create a separated one just for test this and the other fix?

**Comment by CarlosNZ** [comment]
> @CarlosNZ please fix conflicts on this one. I would like to test this with Company license, but not sure how to without merging more branches togheter.... Maybe create a separated one just for test this and the other fix?

Done -- I think this can be put straight to master now, it's a pretty trivial fix.

**Comment by CarlosNZ** [comment]
> I would like to test this with Company license, but not sure how to without merging more branches togheter.

This is a front-end branch -- so just use this branch in the front end with your template in the back end.

**Review by andreievg — APPROVED** [review]
lgtm, although haven't tested

**Comment by nmadruga** [comment]
> > I would like to test this with Company license, but not sure how to without merging more branches togheter.
> 
> This is a front-end branch -- so just use this branch in the front end with your template in the back end.

Yes, you can see I was getting confused with that. Thanks. Just going to check this one using #384 on the back-end and see if can display the listBuilder now.

**Pull request merged**
